# Generated by Django 2.0.4 on 2018-06-02 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Match', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('height', models.PositiveIntegerField(help_text='Altura en cm')),
                ('weight', models.PositiveIntegerField(help_text='Peso en gramos')),
                ('picture', models.ImageField(upload_to='picture_players')),
                ('position', models.CharField(choices=[('BA', 'Base'), ('ES', 'Escolta'), ('AL', 'Alero'), ('AP', 'Ala-pivot'), ('PI', 'Pivot')], max_length=60)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='player',
            field=models.ManyToManyField(to='basket.Player'),
        ),
    ]
