# Generated by Django 2.0.4 on 2018-06-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20180424_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Match', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('player', models.ManyToManyField(to='basket.Player')),
            ],
        ),
    ]
