# Generated by Django 2.0.4 on 2018-06-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_coach_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='player',
        ),
        migrations.AddField(
            model_name='nomination',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Player'),
        ),
    ]
